### ISSUE TITLE
Latest Version with Face Tracking as Public Avatar

### ISSUE THREAD

**Issue by UnderSampled** [cellomonster/vrcfox#2]
The public version of this, which helped me to discover it, seems to be the 1.0 version from April. I would like to use full face tracking, and it sounds like you added that more recently. It's there a newer version I could use to try it out?

**Comment by cellomonster** [comment]
There is! However the head shape is changed and the face tracking honestly doesn’t look that good (the teeth in particular look odd).

https://vrchat.com/home/avatar/avtr_83719901-ed19-4bb6-bacf-9276d5d4de31

**Comment by UnderSampled** [comment]
Thank you! This works great! Only thing missing is tongue tracking 😜.

I was saddened by the lack of creative commons avitars. I'm so happy to find that yours is CC, and also is quite functional and closer to what I was looking for than most others!
