### ISSUE TITLE
Unity Export

### ISSUE THREAD

**Issue by CosmicInfinite** [cellomonster/vrcfox#3]
I am fairly new to this and am still trying to learn Unity and Blender. So whenever I try to export the blender project to Unity using the code given, it gives me an error. How would I fix this.

![_ vrcfox  E__Blender_vrcfox-2 3_vrcfox-2 3_vrcfox blend  - Blender 4 1 4_3_2024 1_25_49 AM](https://github.com/cellomonster/vrcfox/assets/165878476/181c64c5-c6b3-420c-812c-f955ba3759c4)

**Comment by trev3d** [comment]
Unfortunately this script may be broken in the latest version of Blender. I'll try to remember to fix this but please poke me if I forget
